<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="E3539-TECH" name="Parent ChildSubscription Test" tests="1" failures="1" timestamp="22 Aug 2019 04:28:35 GMT" time="68.074" errors="0">
  <testcase name="ChildSubscription" time="59.687" classname="com.ExtramarksWebsite_TestCases.ParentChildSubscriptionTest">
    <failure type="java.lang.AssertionError" message="got actual result as= Login_Fail">
      <![CDATA[java.lang.AssertionError: got actual result as= Login_Fail
	at com.ExtramarksWebsite_TestCases.ParentChildSubscriptionTest.ChildSubscription(ParentChildSubscriptionTest.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- ChildSubscription -->
</testsuite> <!-- Parent ChildSubscription Test -->
