<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="E3539-TECH" name="Parent Dashboard Test" tests="1" failures="1" timestamp="22 Aug 2019 04:27:27 GMT" time="67.991" errors="0">
  <testcase name="DashBoard" time="59.462" classname="com.ExtramarksWebsite_TestCases.ParentDashboardTest">
    <failure type="java.lang.AssertionError" message="got actual result as= Login_Fail">
      <![CDATA[java.lang.AssertionError: got actual result as= Login_Fail
	at com.ExtramarksWebsite_TestCases.ParentDashboardTest.DashBoard(ParentDashboardTest.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- DashBoard -->
</testsuite> <!-- Parent Dashboard Test -->
