<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="E3539-TECH" name="com.ExtramarksWebsite_TestCases.ParentMyChildTest" tests="1" failures="1" timestamp="22 Aug 2019 04:29:44 GMT" time="68.449" errors="0">
  <testcase name="MyChild" time="68.449" classname="com.ExtramarksWebsite_TestCases.ParentMyChildTest">
    <failure type="java.lang.AssertionError" message="got actual result as= Login_Fail">
      <![CDATA[java.lang.AssertionError: got actual result as= Login_Fail
	at org.testng.Assert.fail(Assert.java:94)
	at com.ExtramarksWebsite_TestCases.ParentMyChildTest.MyChild(ParentMyChildTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- MyChild -->
</testsuite> <!-- com.ExtramarksWebsite_TestCases.ParentMyChildTest -->
